Fix Coverity static analysis issues
projectceladon/sensor-vhal pull request #2
Opened 2023-03-17 12:36 UTC by JaikrishnaNemallapudi

Tracked-On: OAM-106686

2023-03-17 12:55 UTC, akodanka approved these changes
LGTM

2023-03-20 06:38 UTC, JeevakaPrabu requested changes
follow this commit message format:

Fix static analysis issues 

Following static analysis issues are addressed
- TAINTED_SCALAR

- Tracked-On: OAM-106686
Signed-off-by: Jaikrishna, Nemallapudi <nemallapudi.jaikrishna@intel.com>

2023-03-20 06:38 UTC, JeevakaPrabu commented on lib/src/sock_utils/SockServer.cpp
> +        size_t length = (strlen(SocketPath.c_str()) < sizeof(addr_un.sun_path)) ?
can we use min function instead of introducing new variable?

2023-03-20 06:38 UTC, JeevakaPrabu commented on lib/src/sock_utils/SockServer.cpp
> +        ret = unlink(SocketPath.c_str());
for the 1st time this will fail as the socket path might not exist. isnt it better to just log and proceed on unlink failure?

2023-03-20 06:38 UTC, JeevakaPrabu commented on lib/src/Sensor.cpp
> +        ALOGW("%s Client Event has invalid sensor type: %d", __func__, cliEvent->header.sensorType);
indent this to 4 spaces

2023-03-20 13:37 UTC, JeevakaPrabu approved these changes

2023-03-21 06:50 UTC, vilasrk approved these changes

2023-03-22 07:20 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/945

Done by "Jaikrishna, Nemallapudi" <nemallapudi.jaikrishna@intel.com>

2023-03-22 15:51 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/485

2023-03-23 04:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/947

2023-03-23 04:56 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/486

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-03-23 06:47 UTC, merged

2023-03-23 06:47 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/android_cloud-mergerequest/builds/498